# Generated by Django 3.2.1 on 2021-07-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210722_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='visit',
            field=models.CharField(choices=[('FTV', 'First Time Visit'), ('RV', 'Repeat Visit')], max_length=30),
        ),
    ]
