# Generated by Django 3.2.1 on 2021-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_encounter_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='diagnosis',
            field=models.CharField(choices=[('Hypertension', 'Hypertension'), ('Diabetes', 'Diabetes'), ('Pneumonia', 'Pneumonia'), ('Malaria', 'Malaria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='visit',
            field=models.CharField(choices=[('First Time Visit', 'First Time Visit'), ('First Time Visit', 'Repeat Visit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
    ]
